---
title: "Machine Learning group project"
author: "Michal Heydel"
date: "27 November 2017"
output: pdf_document
---
```{r}
# input Stata file
library(haven)
ghs<- read_dta("C:/Users/Michal/Documents/01- Master Degree/GitHub/ST443-Project-group9/Stata/stata8/ghs05client.dta")
```



```{r}
setwd("C:/Users/Michal/Documents/01- Master Degree/GitHub/ST443-Project-group9")
```


```{r}
df = ghs
```

```{r}
##Missing values
df[df== -9]<-NA
df[df== -6 ]<-NA
df[df== -7 ]<-NA
df[df== -8 ]<-NA

```

```{r, eval= FALSE}
# df[df== ""] <-NA # DOESNT WORK
```

```{r}
df1 = df
```


```{r}
df1 = df1[-which(is.na(df1$grearn)), ]
```


```{r}
df1 = df1[, -which(colMeans(is.na(df1)) > 0.3)]
```

```{r, eval= FALSE}
write.table(df1, file = "data_reduced_416.csv", col.names = TRUE, na = "NA", sep = "," , row.names = FALSE)
```

```{r}
#df1$se1
```

```{r}
df2 <- read.table(file= "data_reduced_416.csv", na.strings=c("", "NA"), sep=",", header = TRUE)

```

```{r}
df2 = df2[, -which(colMeans(is.na(df2)) > 0.3)]
```

```{r, eval= FALSE}
write.table(df2, file = "data_reduced_411.csv", col.names = TRUE, na = "NA", sep = "," , row.names = FALSE)
```

```{r, eval=FALSE}
head(df2)
```

```{r}
dim(df2)
```

