---
title: "Classifer"
output: pdf_document
---

```{r}
library(tree)
```


```{r}
train_df <- filter(df,df$isTrain==1)
```

```{r}
median(train_df$SalePrice)
```

```{r}
train_df$Classifier <- ifelse(train_df$SalePrice >= 163000,"High","Low")
train_df$Classifier <- as.factor(train_df$Classifier)
```

Classification Tree

```{r}
attach(train_df)
training<- sample(1:nrow(train_df), 1460*0.5)
test.train_df <- train_df[-training,]
Classifier.test <- test.train_df$Classifier
tree.train_df <- tree(Classifier~.-SalePrice, train_df, subset=training)
```

```{r}
tree.pred <- predict(tree.train_df, test.train_df, type="class")
length(tree.pred)
length(Classifier.test)
table(tree.pred, Classifier.test)
mean(tree.pred!=Classifier.test)
```


```{r}
cv.train_df <- cv.tree(tree.train_df, FUN= prune.misclass)
names(cv.train_df)
cv.train_df

par(mfrow=c(1,2))
plot(cv.train_df$size, cv.train_df$dev, type="b")
plot(cv.train_df$k, cv.train_df$dev, type="b")
```

The optimal number of terminal node is 9 and we display the pruned tree graphically

```{r}
par(mfrow=c(1,1))
prune.train_df <-prune.misclass(tree.train_df, best=9)
plot(prune.train_df)
text(prune.train_df, pretty=0)
```
Compute the test error rate using the pruned tree 

```{r}
tree.pred <-predict(prune.train_df, test.train_df, type="class")
table(tree.pred,Classifier.test)
mean(tree.pred!=Classifier.test)
```